import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type User = { id: string; username: string };
type Conversation = { id: string; title: string };
type Message = { id: string; role: string; content: string };
type Root = { id: string; label: string };
type Device = { id: string; name: string; status: string; version: string; roots: Root[] };
type AgentContext = { deviceId: string; rootId: string };

const api = async <T,>(url: string, options?: RequestInit): Promise<T> => {
  const response = await fetch(url, { credentials: 'include', ...options, headers: { ...(options?.body instanceof FormData || options?.body === undefined ? {} : { 'Content-Type': 'application/json' }), ...options?.headers } });
  const data = await response.json();
  if (!response.ok) throw new Error(data.error ?? 'Request failed');
  return data;
};

function Login({ onLogin }: { onLogin: (user: User) => void }) {
  const [username, setUsername] = useState(''); const [password, setPassword] = useState(''); const [error, setError] = useState('');
  return <main className="login"><section><p className="eyebrow">EMBEDDED AI WORKBENCH</p><h1>企业 AI 编程助手</h1><p>服务端 LLM Agent + 本地工程工具。</p><form onSubmit={async event => { event.preventDefault(); try { const result = await api<{user:User}>('/api/auth/login', { method:'POST', body:JSON.stringify({username,password}) }); onLogin(result.user); } catch (e) { setError((e as Error).message); } }}><label>用户名<input value={username} onChange={e=>setUsername(e.target.value)} required /></label><label>密码<input type="password" value={password} onChange={e=>setPassword(e.target.value)} required /></label>{error&&<p className="error">{error}</p>}<button>登录</button></form></section></main>;
}

function AgentPanel({ context, onContext }: { context: AgentContext | null; onContext: (context: AgentContext | null) => void }) {
  const [devices, setDevices] = useState<Device[]>([]); const [pairCode, setPairCode] = useState(''); const [relativePath, setRelativePath] = useState(''); const [taskText, setTaskText] = useState('');
  const load = () => api<{devices:Device[]}>('/api/agents').then(result => { setDevices(result.devices); if (!context && result.devices[0]?.roots[0]) onContext({deviceId:result.devices[0].id,rootId:result.devices[0].roots[0].id}); }).catch(()=>undefined);
  useEffect(() => { load(); const timer=setInterval(load,5000); return ()=>clearInterval(timer); }, []);
  const selected = devices.find(device=>device.id===context?.deviceId);
  const wait = async (taskId:string) => { const timer=setInterval(async()=>{ try { const detail=await api<{task:{status:string},events:Array<unknown>}>(`/api/agent-tasks/${taskId}`); setTaskText(JSON.stringify(detail,null,2)); if(['completed','failed','rejected','expired'].includes(detail.task.status)){clearInterval(timer);load();} } catch { clearInterval(timer); } },1000); };
  const task = async (kind:string, payload:Record<string,unknown>) => { if(!context)return; setTaskText('Agent 正在处理…'); try { const result=await api<{taskId:string}>(`/api/agents/${context.deviceId}/tasks`,{method:'POST',body:JSON.stringify({rootId:context.rootId,kind,payload})}); wait(result.taskId); } catch(e) { setTaskText((e as Error).message); } };
  return <section className="agent-panel"><div className="agent-title"><div><p className="eyebrow">LOCAL TOOL BRIDGE</p><h3>本地 Agent</h3></div><button onClick={async()=>{const result=await api<{code:string}>('/api/agent/pairing-codes',{method:'POST'});setPairCode(result.code);}}>生成配对码</button></div>{pairCode&&<div className="pair-code">在 Agent enroll 中输入：<b>{pairCode}</b></div>}<div className="device-list">{devices.length===0?<p>尚未配对设备。</p>:devices.map(device=><button className={device.id===context?.deviceId?'device selected-device':'device'} key={device.id} onClick={()=>onContext({deviceId:device.id,rootId:device.roots[0]?.id??''})}><i className={device.status}/>{device.name}<small>{device.version} · {device.status}</small></button>)}</div>{selected&&<div className="agent-task"><select value={context?.rootId} onChange={e=>onContext({deviceId:selected.id,rootId:e.target.value})}>{selected.roots.map(root=><option value={root.id} key={root.id}>{root.label}</option>)}</select><button onClick={()=>task('select_root',{})}>更换本地目录</button><input value={relativePath} onChange={e=>setRelativePath(e.target.value)} placeholder="相对路径，例如 src/lcd.c"/><button onClick={()=>task('read_file',{relativePath})}>受控读取文件</button>{taskText&&<pre>{taskText}</pre>}</div>}</section>;
}

function App() {
  const [user,setUser]=useState<User|null>(null); const [conversations,setConversations]=useState<Conversation[]>([]); const [active,setActive]=useState<Conversation|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [requirement,setRequirement]=useState(''); const [files,setFiles]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState(''); const [agentContext,setAgentContext]=useState<AgentContext|null>(null); const [pendingApprovals,setPendingApprovals]=useState<string[]>([]); const [approvalStatus,setApprovalStatus]=useState<Record<string,string>>({});
  const loadConversations=async()=>{const result=await api<{conversations:Conversation[]}>('/api/conversations');setConversations(result.conversations);};
  const open=async(conversation:Conversation)=>{const result=await api<{messages:Message[]}>(`/api/conversations/${conversation.id}`);setActive(conversation);setMessages(result.messages);};
  useEffect(()=>{api<{user:User|null}>('/api/auth/me').then(result=>{setUser(result.user);if(result.user)loadConversations();});},[]);
  if(!user)return <Login onLogin={next=>{setUser(next);loadConversations();}}/>;
  const send=async()=>{if(!requirement.trim()||busy)return;setBusy(true);setError('');try{let current=active;if(!current){const result=await api<{conversation:Conversation}>('/api/conversations',{method:'POST',body:JSON.stringify({title:requirement.slice(0,30)})});current=result.conversation;setActive(current);loadConversations();}let generation:{analysis:string;suggestion:string;code:string;cautions:string[]};let toolTrace:Array<{name:string;result:any}>=[];if(agentContext){const result=await api<{generation:typeof generation;toolTrace:Array<{name:string;result:any}>}>('/api/agent-runs',{method:'POST',body:JSON.stringify({requirement,deviceId:agentContext.deviceId,rootId:agentContext.rootId,sources:[]})});generation=result.generation;toolTrace=result.toolTrace;setPendingApprovals(toolTrace.filter(item=>item.name==='stage_patch'&&item.result?.status==='awaiting_approval').map(item=>String(item.result.taskId)));}else{let fileIds:string[]=[];if(files.length){const form=new FormData();files.forEach(file=>form.append('files',file));const result=await api<{files:{id:string}[]}>('/api/files',{method:'POST',body:form});fileIds=result.files.map(file=>file.id);}const result=await api<{message:Message}>(`/api/conversations/${current.id}/messages`,{method:'POST',body:JSON.stringify({requirement,fileIds})});setMessages(existing=>[...existing,{id:crypto.randomUUID(),role:'user',content:requirement},result.message]);setRequirement('');setFiles([]);return;}const content=`## 分析\n${generation.analysis}\n\n## 建议\n${generation.suggestion}\n\n## 代码草案\n\`\`\`c\n${generation.code}\n\`\`\`\n\n## 注意事项\n${generation.cautions.map(item=>`- ${item}`).join('\n')}`;setMessages(existing=>[...existing,{id:crypto.randomUUID(),role:'user',content:requirement},{id:crypto.randomUUID(),role:'assistant',content:content+"\\n\\nAgent tool trace:\\n"+JSON.stringify(toolTrace,null,2)}]);setRequirement('');}catch(e){setError((e as Error).message);}finally{setBusy(false);}};
  const approve=async(taskId:string)=>{setApprovalStatus(status=>({...status,[taskId]:"写入中…"}));try{await api(`/api/agent-tasks/${taskId}/approve`,{method:"POST"});const timer=setInterval(async()=>{try{const detail=await api<{task:{status:string}}>(`/api/agent-tasks/${taskId}`);if(["completed","failed","rejected","expired"].includes(detail.task.status)){clearInterval(timer);setApprovalStatus(status=>({...status,[taskId]:detail.task.status}));setPendingApprovals(items=>items.filter(item=>item!==taskId));}}catch{clearInterval(timer);setApprovalStatus(status=>({...status,[taskId]:"查询失败"}));}},1000);}catch(e){setApprovalStatus(status=>({...status,[taskId]:(e as Error).message}));}};
  return <div className="shell"><aside><div className="brand">企业 AI 编程助手</div><button className="new" onClick={()=>{setActive(null);setMessages([]);}}>+ 新建对话</button><div className="history">{conversations.map(conversation=><button key={conversation.id} onClick={()=>open(conversation)} className={active?.id===conversation.id?'selected':''}>{conversation.title}</button>)}</div><AgentPanel context={agentContext} onContext={setAgentContext}/><div className="account"><span>{user.username}</span><button onClick={async()=>{await api('/api/auth/logout',{method:'POST'});setUser(null);}}>退出</button></div></aside><main className="chat"><header><div><p className="eyebrow">SERVER LLM AGENT</p><h2>{active?.title??'新建代码草案'}</h2></div><span className="badge">{agentContext?'已连接本地工程工具':'仅生成草案'}</span></header><section className="messages">{messages.length===0&&<div className="empty"><h3>描述你希望完成的工程任务</h3><p>选择本地 Agent 后，服务端 LLM 可以读取并修改授权工程。</p></div>}{messages.map(message=><article key={message.id} className={message.role}><div className="role">{message.role==='user'?'你':'AI Agent'}</div><pre>{message.content}</pre></article>)}</section>{pendingApprovals.length>0&&<div className="approval-list"><p>检测到待确认补丁，确认后才会写入本地工程。</p>{pendingApprovals.map(taskId=><span key={taskId}><button onClick={()=>approve(taskId)}>确认写入补丁</button><small>{approvalStatus[taskId]??"待确认"}</small></span>)}</div>}<footer><label className="upload">上传源码<input type="file" multiple accept=".c,.h,.txt,.md" onChange={event=>setFiles(Array.from(event.target.files??[]))}/><span>{files.length?`已选 ${files.length} 个文件`:'支持 .c / .h / .txt / .md'}</span></label><textarea value={requirement} onChange={event=>setRequirement(event.target.value)} placeholder={agentContext?'描述要让 Agent 读取或修改的本地工程任务…':'描述你希望生成的代码草案…'}/><div className="sendrow">{error&&<span className="error">{error}</span>}<button disabled={busy||!requirement.trim()} onClick={send}>{busy?(agentContext?'Agent 工作中…':'正在生成…'):(agentContext?'运行 Agent':'生成代码草案')}</button></div></footer></main></div>;
}

createRoot(document.getElementById('root')!).render(<App/>);
