import { useEffect, useState } from 'react';
import { createRoot } from 'react-dom/client';
import './styles.css';

type User = { id: string; username: string };
type Conversation = { id: string; title: string; createdAt: string };
type Message = { id: string; role: string; content: string; createdAt: string };
const api = async <T,>(url: string, options?: RequestInit): Promise<T> => { const res = await fetch(url, { credentials: 'include', ...options, headers: { ...(options?.body instanceof FormData ? {} : {'Content-Type':'application/json'}), ...options?.headers } }); const data = await res.json(); if (!res.ok) throw new Error(data.error ?? '请求失败'); return data; };

function Login({ onLogin }: { onLogin: (u: User) => void }) { const [username,setUsername]=useState(''); const [password,setPassword]=useState(''); const [error,setError]=useState(''); return <main className="login"><section><p className="eyebrow">EMBEDDED AI WORKBENCH</p><h1>企业 AI 编程助手</h1><p>将公司代码规范带入每一次嵌入式开发对话。</p><form onSubmit={async e=>{e.preventDefault();try { const r=await api<{user:User}>('/api/auth/login',{method:'POST',body:JSON.stringify({username,password})});onLogin(r.user)}catch(err){setError((err as Error).message)}}}><label>用户名<input value={username} onChange={e=>setUsername(e.target.value)} autoComplete="username" required/></label><label>密码<input value={password} onChange={e=>setPassword(e.target.value)} type="password" autoComplete="current-password" required/></label>{error&&<p className="error">{error}</p>}<button>登录</button></form></section></main> }

function App() { const [user,setUser]=useState<User|null>(null); const [conversations,setConversations]=useState<Conversation[]>([]); const [active,setActive]=useState<Conversation|null>(null); const [messages,setMessages]=useState<Message[]>([]); const [requirement,setRequirement]=useState(''); const [files,setFiles]=useState<File[]>([]); const [busy,setBusy]=useState(false); const [error,setError]=useState('');
  const loadConversations=async()=>{const r=await api<{conversations:Conversation[]}>('/api/conversations');setConversations(r.conversations)};
  const open=async(c:Conversation)=>{const r=await api<{messages:Message[]}>(`/api/conversations/${c.id}`);setActive(c);setMessages(r.messages)};
  useEffect(()=>{api<{user:User|null}>('/api/auth/me').then(r=>{setUser(r.user);if(r.user)loadConversations()}).catch(()=>undefined)},[]);
  if(!user) return <Login onLogin={u=>{setUser(u);loadConversations()}}/>;
  const send=async()=>{if(!requirement.trim()||busy)return;setBusy(true);setError('');try { let fileIds:string[]=[];if(files.length){const form=new FormData();files.forEach(f=>form.append('files',f));const uploaded=await api<{files:{id:string}[]}>('/api/files',{method:'POST',body:form});fileIds=uploaded.files.map(f=>f.id)} let current=active;if(!current){const r=await api<{conversation:Conversation}>('/api/conversations',{method:'POST',body:JSON.stringify({title:requirement.slice(0,30)})});current=r.conversation;setActive(current);await loadConversations()}const r=await api<{message:Message}>(`/api/conversations/${current.id}/messages`,{method:'POST',body:JSON.stringify({requirement,fileIds})});setMessages(m=>[...m,{id:crypto.randomUUID(),role:'user',content:requirement,createdAt:new Date().toISOString()},r.message]);setRequirement('');setFiles([])}catch(err){setError((err as Error).message)}finally{setBusy(false)}};
  return <div className="shell"><aside><div className="brand">企业 AI 编程助手</div><button className="new" onClick={()=>{setActive(null);setMessages([])}}>+ 新建对话</button><div className="history">{conversations.map(c=><button key={c.id} onClick={()=>open(c)} className={active?.id===c.id?'selected':''}>{c.title}</button>)}</div><div className="account"><span>{user.username}</span><button onClick={async()=>{await api('/api/auth/logout',{method:'POST'});setUser(null)}}>退出</button></div></aside><main className="chat"><header><div><p className="eyebrow">MVP · 模拟模型</p><h2>{active?.title??'新建代码草案'}</h2></div><span className="badge">规范已注入</span></header><section className="messages">{messages.length===0&&<div className="empty"><h3>从一个小的嵌入式需求开始</h3><p>例如：根据现有 LCD 驱动，添加电子钟冒号闪烁显示。</p></div>}{messages.map(m=><article key={m.id} className={m.role}><div className="role">{m.role==='user'?'你':'AI 助手'}</div><pre>{m.content}</pre>{m.role==='assistant'&&<button className="copy" onClick={()=>navigator.clipboard.writeText(m.content)}>复制结果</button>}</article>)}</section><footer><label className="upload">上传源码<input type="file" multiple accept=".c,.h,.txt,.md" onChange={e=>setFiles(Array.from(e.target.files??[]))}/><span>{files.length?`已选 ${files.length} 个文件`:'支持 .c / .h / .txt / .md'}</span></label><textarea value={requirement} onChange={e=>setRequirement(e.target.value)} placeholder="描述你希望完成的代码修改…"/><div className="sendrow">{error&&<span className="error">{error}</span>}<button disabled={busy||!requirement.trim()} onClick={send}>{busy?'正在生成…':'生成代码草案'}</button></div></footer></main></div> }
createRoot(document.getElementById('root')!).render(<App/>);
